### ISSUE TITLE
Cannot launch Electrum wallet on macOS 10.13.5

### ISSUE THREAD

**Issue by greerso** [straks/electrum-stak#2]
When launching from cli

```
./Electrum-STAK
Traceback (most recent call last):
  File "electrum-stak", line 376, in <module>
  File "Electrum_STAK-3.0.5-py3.6.egg/electrum_stak/daemon.py", line 126, in __init__
  File "Electrum_STAK-3.0.5-py3.6.egg/electrum_stak/network.py", line 167, in __init__
  File "Electrum_STAK-3.0.5-py3.6.egg/electrum_stak/blockchain.py", line 105, in read_blockchains
  File "Electrum_STAK-3.0.5-py3.6.egg/electrum_stak/blockchain.py", line 422, in can_connect
TypeError: 'NoneType' object is not subscriptable
[77167] Failed to execute script electrum-stak
```

**Comment by ekamgit** [comment]
There is a lock folder in the data directory that will contain a file. If you delete that file then the wallet will load.

Only delete that file, nothing else.

We are aware of this issue and it has been fixed, just need to push the osx wallet.

**Comment by greerso** [comment]
Thanks for the quick reply.  I dont see it in ~/.electrum-stak.
```
-rw-r--r--  1     22M Jun 22 17:51 blockchain_headers
drwx------  7    224B Jun 18 22:25 certs
-rw-------  1    446B Jun 22 18:54 config
-rw-r--r--  1      0B Jul 10 22:39 daemon
drwxr-xr-x  3     96B Jun 22 17:51 forks
-rw-r--r--  1    171B Jun 22 17:20 recent_servers
drwx------  3     96B Jun 22 18:54 wallets
```

I'll wait for the next version.

**Comment by ekamgit** [comment]
My bad, I meant the forks folder. Sorry.

**Comment by greerso** [comment]
That did it.  Thanks!
